### ISSUE TITLE
praw.exceptions.InvalidURL  Invalid URL: https://i.reddit.it/someimage.jpg

### ISSUE THREAD

**Issue by anoduck** [toadlyBroodle/twatbot#3]
Going to try to assist as much as I can to find a solution for this one. Scraped everything alright...I believe. But was unable to submit promotions. Raised the following error: 

```
spam-bot-3000.py:371: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ret_code is 3:
spam-bot-3000.py:396: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ret_code is 0:
spam-bot-3000.py:398: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif ret_code is 2:
spam-bot-3000.py:400: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif ret_code is 3:
spam-bot-3000.py:498: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ret_code is 2: # HTTPError returned from query, move onto next query
spam-bot-3000.py:677: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ret_code is 3:
spam-bot-3000.py:688: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif ret_code is 2: # automation detected
spam-bot-3000.py:691: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif ret_code is 3: # serious error returned, terminate activity
Authenticating...
2020Jul22 06:07:38 Authenticated as: Some user
Traceback (most recent call last):
  File "spam-bot-3000.py", line 735, in <module>
    main(sys.argv[1:])
  File "spam-bot-3000.py", line 722, in main
    replyReddit()
  File "spam-bot-3000.py", line 130, in replyReddit
    submission = reddit.submission(url=pd[1])
  File "/usr/local/lib/python3.8/site-packages/praw/reddit.py", line 800, in submission
    return models.Submission(self, id=id, url=url)
  File "/usr/local/lib/python3.8/site-packages/praw/models/reddit/submission.py", line 540, in __init__
    self.id = self.id_from_url(url)
  File "/usr/local/lib/python3.8/site-packages/praw/models/reddit/submission.py", line 427, in id_from_url
    raise InvalidURL(url)
praw.exceptions.InvalidURL: Invalid URL: https://i.redd.it/xxxxx.jpg
```

I believe that it is scraping not the post link but the contents of the post itself.

**Comment by clankwright** [comment]
Hmm, sorry reddit portion was not tested as extensively as was twitter; not surprised there are bugs. Have mostly abandoned this repo for time being, so you're on your own for now.

**Comment by anoduck** [comment]
These are very troubling times in the kingdom... sad news, bro, sad news indeed. 🙅 😞
